# Generated by Django 6.0 on 2025-12-31 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('tax_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Import', 'Nhập'), ('Export', 'Xuất')], max_length=10)),
                ('partner_bill', models.CharField(default='', max_length=200)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_deadline', models.DateTimeField(null=True)),
                ('authorization_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('Rejected', 'Không được duyệt'), ('Pending', 'Chờ duyệt'), ('Authorized', 'Đã duyệt, chờ hoàn thành'), ('Completed', 'Đã hoàn thành')], default='Pending', max_length=15)),
            ],
            options={
                'permissions': [('authorize_transaction', 'Can authorize or reject a transaction'), ('complete_transaction', 'Can complete transaction')],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('report_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=250)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('packaging', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('None', ''), ('Piece', 'Cái'), ('Box', 'Hộp'), ('Bottle', 'Chai'), ('Jar', 'Lọ'), ('Tube', 'Tuýp'), ('Bag', 'Túi'), ('Sack', 'Bao'), ('Blister', 'Vỉ'), ('Pill', 'Viên')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ivm.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ivm.item')),
            ],
        ),
    ]
