# Generated by Django 6.0 on 2026-01-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivm', '0002_initial'),
        ('tasks', '0003_task_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ivm.transaction'),
        ),
    ]
